import streamlit as st
import pandas as pd
import plotly.express as px

# 1. IMPORT OUR CLEANING FUNCTION
from data_processing import load_and_clean_data

# 2. SET PAGE CONFIGURATION
st.set_page_config(page_title="Fee & Profitability", page_icon="💰", layout="wide")

# 3. LOAD THE DATA
df = load_and_clean_data()

# 4. SAFETY CHECK
if not df.empty:
    st.title("Fee Structure & Profitability Analysis")
    st.markdown("Analyze how fee structures relate to client income, loyalty, and total fees generated.")

    # 5. PAGE LAYOUT
    col1, col2 = st.columns(2)

    with col1:
        # 6. Chart 1: Total Fees by Structure (Bar)
        st.subheader("Total Fees Generated by Fee Structure")
        
        # We need to calculate Total Fees first
        df['Total Fees'] = df['Total Loan'] * df['Processing Fees']
        
        # Group by 'Fee Structure' and sum the 'Total Fees'
        df_fees = df.groupby('Fee Structure')['Total Fees'].sum().reset_index()
        
        fig_fees_bar = px.bar(
            df_fees,
            x='Fee Structure',
            y='Total Fees',
            color='Fee Structure',
            title='Total Fees Generated'
        )
        st.plotly_chart(fig_fees_bar, use_container_width=True)

        # 7. Chart 2: Loyalty vs. Fee Structure (Stacked Bar)
        st.subheader("Loyalty Mix by Fee Structure")
        
        # --- Manual Percentage Calculation ---
        # 1. Get Raw Grouped Counts
        df_loyalty_raw = df.groupby(['Fee Structure', 'Loyalty Classification'])['Client ID'].count().reset_index(name='Client Count')
        # 2. Get Group Totals
        df_totals = df_loyalty_raw.groupby('Fee Structure')['Client Count'].sum().reset_index(name='Total Clients')
        # 3. Merge Totals Back
        df_loyalty = df_loyalty_raw.merge(df_totals, on='Fee Structure')
        # 4. Calculate Percentage
        df_loyalty['Percentage'] = df_loyalty['Client Count'] / df_loyalty['Total Clients']
        
        fig_loyalty_stack = px.bar(
            df_loyalty,
            x='Fee Structure',
            y='Percentage',
            color='Loyalty Classification',
            title='Client Loyalty Mix (Normalized)',
            labels={'Percentage': 'Percentage of Clients'}
        )
        fig_loyalty_stack.update_layout(yaxis_tickformat=".0%")
        st.plotly_chart(fig_loyalty_stack, use_container_width=True)

    with col2:
        # 8. Chart 3: Income vs. Fee Structure (Box Plot)
        st.subheader("Income Distribution by Fee Structure")
        
        # A box plot is perfect for comparing distributions
        fig_income_box = px.box(
            df,
            x='Fee Structure',
            y='Estimated Income',
            color='Fee Structure',
            title='Estimated Income by Fee Structure'
        )
        # We limit the y-axis to make it readable (excluding extreme outliers)
        fig_income_box.update_layout(yaxis_range=[0, 800000])
        st.plotly_chart(fig_income_box, use_container_width=True)
        
        # 9. Chart 4: Clients per Fee Structure (Pie)
        st.subheader("Client Distribution by Fee Structure")
        df_pie = df['Fee Structure'].value_counts().reset_index()
        df_pie.columns = ['Fee Structure', 'Client Count']
        
        fig_pie = px.pie(
            df_pie,
            names='Fee Structure',
            values='Client Count',
            title='Percentage of Clients in Each Fee Structure'
        )
        st.plotly_chart(fig_pie, use_container_width=True)

else:
    st.warning("Data could not be loaded. Please check your data files.")